import sys; sys.path.insert(0, __import__("os").path.dirname(__import__("os").path.abspath(__file__)))
from lib import *
R = "/tmp/e2e-claude"; newrepo(R)
sh("dibs init --agents claude", cwd=R)
sh("git add -A && git commit -qm 'dibs init'", cwd=R)
E = dict(ENV, CLAUDE_CONFIG_DIR="/tmp/cc-home", ANTHROPIC_BASE_URL="http://127.0.0.1:18800", ANTHROPIC_API_KEY="sk-ant-dummy",
         DISABLE_AUTOUPDATER="1", CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1")
shutil.rmtree("/tmp/cc-home", ignore_errors=True); os.makedirs("/tmp/cc-home")
def claude(prompt, mode="acceptEdits", cont=True):
    args = ["claude", "-p", prompt, "--permission-mode", mode, "--model", "claude-sonnet-4-5", "--output-format", "text"]
    if cont: args.insert(1, "--continue")
    return sh(args, cwd=R, env=E)
clear_log()
print("== turn 1: claude writes api.py")
script([{"tool": "Write", "input": {"file_path": f"{R}/api.py", "content": V1}}, {"text": "wrote api.py"}])
claude("create api.py", cont=False)
ok(open(f"{R}/api.py").read() == V1, "claude Write created api.py")
print("== human edits api.py by hand"); human_edit(R)
clear_log()
print("== turn 2: claude reads, then rewrites from memory")
script([{"tool": "Read", "input": {"file_path": f"{R}/api.py"}},
        {"tool": "Write", "input": {"file_path": f"{R}/api.py", "content": V2}}, {"text": "added logging"}])
claude("add logging")
txt = all_text()
ok("Since your last turn" in txt and "timeout=30" in txt, "UserPromptSubmit brief reached the model")
tr = tool_results(); print("tool results:", [t[:300] for t in tr])
ok(any("would undo changes the human made" in t for t in tr), "PreToolUse guard message reached the model")
ok(HUMAN in open(f"{R}/api.py").read(), "human line survived the Write")
clear_log()
print("== turn 3: claude builds on the human line")
script([{"tool": "Edit", "input": {"file_path": f"{R}/api.py", "old_string": "import requests\n", "new_string": "import logging\nimport requests\n"}},
        {"text": "ok"}])
claude("add logging import")
ok(open(f"{R}/api.py").read().startswith("import logging\nimport requests") and HUMAN in open(f"{R}/api.py").read(), "non-reverting Edit allowed")
clear_log()
print("== turn 4: claude reverts through Bash (cannot be stopped in advance)")
script([{"tool": "Bash", "input": {"command": "sed -i 's/timeout=30, verify=\"ca.pem\")/timeout=10)/' api.py", "description": "reset timeout"}},
        {"text": "reset"}])
claude("reset the timeout", mode="bypassPermissions")
show(R)
tr = tool_results(); print("tool results:", [t[:400] for t in tr])
txt = all_text()
ok("undid lines the human edited" in txt, "PostToolUse revert note reached the model")
st = sh("NO_COLOR=1 dibs status", cwd=R)
ok("Reverted human lines" in st.stdout, "dibs status lists the revert")
c = sh("git add -A && git commit -qm wip", cwd=R)
ok(c.returncode != 0, "pre-commit blocks the commit")
sh("dibs restore api.py", cwd=R); show(R)
s = open(f"{R}/api.py").read()
ok(HUMAN in s and s.startswith("import logging"), "restore put back the human line and kept the agent's import")
c = sh("git add -A && git commit -qm wip", cwd=R)
ok(c.returncode == 0, "commit allowed after restore")
sh("NO_COLOR=1 dibs log -n 20", cwd=R)
sh("cat .git/dibs/hook-errors.log", cwd=R)
print("RESULTS", sum(r for _, r in RESULTS), "/", len(RESULTS))
