import sys; sys.path.insert(0, __import__("os").path.dirname(__import__("os").path.abspath(__file__)))
from lib import *
R = "/tmp/e2e-codex"; newrepo(R)
sh("dibs init --agents codex", cwd=R)
sh("git add -A && git commit -qm 'dibs init'", cwd=R)
E = dict(ENV, CODEX_HOME="/tmp/codex-home", MOCK_API_KEY="x")
TRUST = sys.argv[1:] != ["notrust"]
def codex(prompt, resume=True):
    a = ["codex", "exec", "--skip-git-repo-check"] + (["--dangerously-bypass-hook-trust"] if TRUST else [])
    if resume: a += ["resume", "--last"]
    return sh(a + [prompt], cwd=R, env=E, quiet=True)
def patch(body): return {"tool": "apply_patch", "custom": True, "input": body}
clear_log()
print("== turn 1: codex adds api.py via apply_patch")
add = "*** Begin Patch\n*** Add File: api.py\n" + "".join("+" + l + "\n" for l in V1.rstrip("\n").split("\n")) + "*** End Patch\n"
script([patch(add), {"text": "created"}])
r = codex("create api.py", resume=False); print(r.stdout[-300:], [l for l in r.stderr.splitlines() if "hook" in l.lower()][:12])
first = log()
print("tools:", first[0]["tools"] if first else None)
ok(os.path.exists(f"{R}/api.py") and open(f"{R}/api.py").read() == V1, "codex apply_patch created api.py")
print("== human edits"); human_edit(R)
clear_log()
print("== turn 2: codex patches from its stale memory")
upd = ("*** Begin Patch\n*** Update File: api.py\n@@\n-import requests\n+import logging\n+import requests\n@@ def fetch(url):\n"
       "-    r = requests.get(url, timeout=30, verify=\"ca.pem\")\n+    log.info(\"GET %s\", url)\n+    r = requests.get(url, timeout=10)\n*** End Patch\n")
script([patch(upd), {"text": "added logging"}])
r = codex("add logging"); print([l for l in r.stderr.splitlines() if "hook" in l.lower() or "dibs" in l][:12])
txt = all_text()
ok("Since your last turn" in txt and "timeout=30" in txt, "UserPromptSubmit brief reached the model")
tr = tool_results(); print("tool results:", [t[:300] for t in tr])
ok(any("would undo changes the human made" in t for t in tr), "PreToolUse deny reason reached the model")
ok(HUMAN in open(f"{R}/api.py").read(), "human line survived the patch")
clear_log()
print("== turn 3: codex reverts via shell")
script([{"tool": "exec_command", "input": {"cmd": "sed -i 's/timeout=30, verify=\"ca.pem\")/timeout=10)/' api.py"}}, {"text": "reset"}])
r = codex("reset timeout"); print([l for l in r.stderr.splitlines() if "hook" in l.lower()][:12])
show(R)
txt = all_text()
ok("undid lines the human edited" in txt, "PostToolUse revert note reached the model")
st = sh("NO_COLOR=1 dibs status", cwd=R, quiet=True)
ok("Reverted human lines" in st.stdout, "dibs status lists the revert")
sh("dibs restore api.py", cwd=R)
ok(HUMAN in open(f"{R}/api.py").read(), "restore put back the human line")
sh("NO_COLOR=1 dibs log -n 20", cwd=R)
sh("cat .git/dibs/hook-errors.log", cwd=R)
print("RESULTS", sum(r for _, r in RESULTS), "/", len(RESULTS))
