import sys; sys.path.insert(0, __import__("os").path.dirname(__import__("os").path.abspath(__file__)))
from lib import *
R = "/tmp/e2e-gemini"; newrepo(R)
sh("dibs init --agents gemini", cwd=R, quiet=True)
sh("git add -A && git commit -qm 'dibs init'", cwd=R)
shutil.rmtree('/tmp/gm-home', ignore_errors=True); os.makedirs('/tmp/gm-home/.gemini')
json.dump({"security": {"auth": {"selectedType": "gemini-api-key"}}}, open('/tmp/gm-home/.gemini/settings.json', 'w'))
TRUST = sys.argv[1:] != ["notrust"]
if TRUST: json.dump({R: "TRUST_FOLDER"}, open('/tmp/gm-home/.gemini/trustedFolders.json', 'w'))
E = dict(ENV, GEMINI_CLI_HOME='/tmp/gm-home', GOOGLE_GEMINI_BASE_URL='http://127.0.0.1:18800', GEMINI_API_KEY='x')
def gemini(prompt):
    r = sh(['gemini', '-p', prompt, '--yolo', '-m', 'gemini-2.5-pro'], cwd=R, env=E, quiet=True)
    print("  out:", r.stdout.strip()[-200:]); return r
clear_log()
print("== turn 1: gemini write_file")
script([{"tool": "write_file", "input": {"file_path": f"{R}/api.py", "content": V1}}, {"text": "created"}])
gemini("create api.py")
ok(os.path.exists(f"{R}/api.py") and open(f"{R}/api.py").read() == V1, "gemini write_file created api.py")
print("== human edits"); human_edit(R)
clear_log()
print("== turn 2: gemini rewrites from memory with write_file")
script([{"tool": "write_file", "input": {"file_path": f"{R}/api.py", "content": V2}}, {"text": "added logging"}])
gemini("add logging")
txt = all_text()
ok("Since your last turn" in txt and "timeout=30" in txt, "BeforeAgent brief reached the model")
tr = tool_results(); print("tool results:", [t[:300] for t in tr])
ok(any("would undo changes the human made" in t for t in tr), "BeforeTool deny reason reached the model")
ok(HUMAN in open(f"{R}/api.py").read(), "human line survived write_file")
clear_log()
print("== turn 3: gemini replace that builds on the human line")
script([{"tool": "replace", "input": {"file_path": f"{R}/api.py", "old_string": "import requests\n", "new_string": "import logging\nimport requests\n", "instruction": "add import"}}, {"text": "ok"}])
gemini("add import")
s = open(f"{R}/api.py").read()
ok(s.startswith("import logging") and HUMAN in s, "non-reverting replace allowed")
clear_log()
print("== turn 4: gemini replace that reverts")
script([{"tool": "replace", "input": {"file_path": f"{R}/api.py", "old_string": HUMAN, "new_string": "    r = requests.get(url, timeout=10)", "instruction": "reset"}}, {"text": "ok"}])
gemini("reset timeout")
ok(HUMAN in open(f"{R}/api.py").read(), "reverting replace blocked")
clear_log()
print("== turn 5: gemini reverts via run_shell_command")
script([{"tool": "run_shell_command", "input": {"command": "sed -i 's/timeout=30, verify=\"ca.pem\")/timeout=10)/' api.py", "description": "reset"}}, {"text": "reset"}])
gemini("reset timeout via shell")
show(R)
txt = all_text()
ok("undid lines the human edited" in txt, "AfterTool revert note reached the model")
sh("dibs restore api.py", cwd=R)
s = open(f"{R}/api.py").read()
ok(HUMAN in s and s.startswith("import logging"), "restore put back the human line")
sh("NO_COLOR=1 dibs log -n 20", cwd=R)
sh("cat .git/dibs/hook-errors.log", cwd=R)
print("RESULTS", sum(r for _, r in RESULTS), "/", len(RESULTS))
